# Generated by Django 5.2.12 on 2026-03-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kitob nomi')),
                ('author', models.CharField(max_length=150, verbose_name='Muallif')),
                ('genre', models.CharField(max_length=100, verbose_name='Janr')),
                ('description', models.TextField(verbose_name='Qisqacha izoh')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Kitob rasmi')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Sevimli')),
            ],
        ),
    ]
